#!/Users/ymq/bin/python
# create host python recipe for build moudle and install to host python 
import os
import sys
import codecs
import json
from pathlib import Path
import sh
import shutil

recipe_pattern="""
from os.path import join
from kivy_ios.toolchain import HostRecipe, shprint, cache_execution
from kivy_ios.recipes.pypi_info import get_version_url
from kivy_ios.context_managers import cd, python_path
import sh

class TempRecipe(HostRecipe):
	depends = ["openssl", "hostpython3", "python3", "host_setuptools3"]
	version, url = get_version_url('%(name)s')

	def get_recipe_env(self, arch):
		env = super().get_recipe_env(arch)
		env['PYTHONPATH'] = join(self.ctx.dist_dir, 'hostpython3', \
									'lib', 'python3.9', 'site-packages')
		return env

	@cache_execution
	def install(self):
		arch = self.filtered_archs[0]
		build_dir = self.get_build_dir(arch.arch)
		hostpython = sh.Command(self.ctx.hostpython)

		with python_path(self.ctx.site_packages_dir):
			with cd(build_dir):
				python_prefix = join(self.ctx.dist_dir, 'hostpython3')
				shprint(hostpython, "setup.py", "install",
						f"--prefix={python_prefix}")

recipe = TempRecipe()
"""
class PythonRecipeCreator:
	def __init__(self, name, folder=None):
		self.name = name
		self.folder = folder if folder else self.name
		self.env = {}

	def run(self):
		self.load_env()
		self.gen_recipe_folder()

	def load_env(self):
		home = str(Path.home())
		fp = os.path.join(home, '.iospr.json')
		# if Path(fp).is_file():
		if os.path.isfile(fp):
			with codecs.open(fp, 'r', 'utf-8') as f:
				d = json.load(f)
				self.env = d
			print(self.env)
			return 
		print(f'~/.iospr.json {fp} not found')

	def gen_recipe_file(self, folder):
		fp = os.path.join(folder, '__init__.py')
		recipe = recipe_pattern % {
			'name':self.name
		}
		with codecs.open(fp, 'w', 'utf-8') as f:
			f.write(recipe)

	def gen_recipe_folder(self):
		rfp = os.path.join(self.env['LOCAL_RECIPES_PATH'], self.folder)
		rrfp = os.path.join(self.env['IOS_RECIPES_PATH'], self.folder)
		try:
			sh.mkdir(rfp)
		except:
			pass
		try:
			sh.ln('-s', rfp, rrfp)
		except:
			pass
		self.gen_recipe_file(rfp)

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print(f'Usage:\n{sys.argv[0]} module_name [ recipe_folder ]')
		sys.exit(1)

	folder = None
	if len(sys.argv) > 2:
		folder = sys.argv[2]
	prc = PythonRecipeCreator(sys.argv[1], folder=folder)
	prc.run()

