#!/bin/sh
pushd
cd ios
for name in $(ls); do
	echo ln -s `pwd`/$name /usr/local/lib/python3.9/site-packages/kivy_ios/recipes
	ln -s `pwd`/$name /usr/local/lib/python3.9/site-packages/kivy_ios/recipes
done
popd
