#!/Users/ymq/bin/python
import os
import sys
import codecs
import json
from pathlib import Path
import sh
import shutil

recipe_pattern="""
from kivy_ios.toolchain import PythonRecipe
from kivy_ios.recipes.pypi_info import get_version_url
class TmpRecipe(PythonRecipe):
   version, url = get_version_url('%(name)s', version='%(version)s')
   depends = ["python"]

recipe = TmpRecipe()
"""
class PythonRecipeCreator:
	def __init__(self, name, folder=None):
		b = name.split('==', 1)
		self.name = b[0]
		self.version = '' if len(b) == 1 else b[1]
		self.folder = folder if folder else self.name
		self.env = {}

	def run(self):
		self.load_env()
		self.gen_recipe_folder()

	def load_env(self):
		home = str(Path.home())
		fp = os.path.join(home, '.iospr.json')
		# if Path(fp).is_file():
		if os.path.isfile(fp):
			with codecs.open(fp, 'r', 'utf-8') as f:
				d = json.load(f)
				self.env = d
			print(self.env)
			return 
		print(f'~/.iospr.json {fp} not found')

	def gen_recipe_file(self, folder):
		fp = os.path.join(folder, '__init__.py')
		recipe = recipe_pattern % {
			'name':self.name,
			'version':self.version
		}
		with codecs.open(fp, 'w', 'utf-8') as f:
			f.write(recipe)

	def gen_recipe_folder(self):
		rfp = os.path.join(self.env['LOCAL_RECIPES_PATH'], self.folder)
		rrfp = os.path.join(self.env['IOS_RECIPES_PATH'], self.folder)
		try:
			sh.mkdir(rfp)
		except:
			pass
		try:
			sh.ln('-s', rfp, rrfp)
		except:
			pass
		self.gen_recipe_file(rfp)

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print(f'Usage:\n{sys.argv[0]} module_name [ recipe_folder ]')
		sys.exit(1)

	folder = None
	if len(sys.argv) > 2:
		folder = sys.argv[2]
	prc = PythonRecipeCreator(sys.argv[1], folder=folder)
	prc.run()

